"""Added State.color, State.limit, and State.description

Revision ID: 014a5de3792b
Revises: 1c1d32bc1d1f
Create Date: 2024-07-22 15:31:54.820106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014a5de3792b'
down_revision: Union[str, None] = '1c1d32bc1d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state', sa.Column('color', sa.String(length=10), nullable=True))
    op.add_column('state', sa.Column('limit', sa.Numeric(), nullable=True))
    op.add_column('state', sa.Column('description', sa.String(length=280), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('state', 'description')
    op.drop_column('state', 'limit')
    op.drop_column('state', 'color')
    # ### end Alembic commands ###
