"""removed issue.color_id, issue.color color.states and replaced with issue.color and color.hex_code and color.name

Revision ID: 03e182be8297
Revises: 0f68e1ed2ad3
Create Date: 2024-07-26 14:09:01.621046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e182be8297'
down_revision: Union[str, None] = '0f68e1ed2ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('hex_code', sa.String(length=7), nullable=False))
    op.alter_column('color', 'name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=120),
               nullable=True)
    op.add_column('state', sa.Column('color', sa.String(length=7), nullable=True))
    op.drop_constraint('state_color_id_fkey', 'state', type_='foreignkey')
    op.drop_column('state', 'color_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state', sa.Column('color_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('state_color_id_fkey', 'state', 'color', ['color_id'], ['id'])
    op.drop_column('state', 'color')
    op.alter_column('color', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('color', 'hex_code')
    # ### end Alembic commands ###
