"""Added Color model, rm State.color and mapped State to Color with one-to-many rel

Revision ID: 04184a9bd72e
Revises: 014a5de3792b
Create Date: 2024-07-22 15:59:22.474563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04184a9bd72e'
down_revision: Union[str, None] = '014a5de3792b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('state', sa.Column('color_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'state', 'color', ['color_id'], ['id'])
    op.drop_column('state', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state', sa.Column('color', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'state', type_='foreignkey')
    op.drop_column('state', 'color_id')
    op.drop_table('color')
    # ### end Alembic commands ###
