"""Issue.issue_key added and Issue.state_id is nullable

Revision ID: 55ea38f88555
Revises: 72e7820968aa
Create Date: 2024-07-19 14:16:33.798017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ea38f88555'
down_revision: Union[str, None] = '72e7820968aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('issue_key', sa.String(), nullable=False))
    op.alter_column('issue', 'state_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issue', 'state_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('issue', 'issue_key')
    # ### end Alembic commands ###
