"""Fix typo in User.oauth_accounts field

Revision ID: 72e7820968aa
Revises: ae28dc4554f7
Create Date: 2024-07-16 13:28:40.034472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e7820968aa'
down_revision: Union[str, None] = 'ae28dc4554f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
