"""User.fullname is nullable

Revision ID: 7bb4610376ed
Revises: 7ff0a8388f85
Create Date: 2024-07-16 12:33:36.157139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb4610376ed'
down_revision: Union[str, None] = '7ff0a8388f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'issue', ['id'])
    op.create_unique_constraint(None, 'label', ['id'])
    op.create_unique_constraint(None, 'project', ['id'])
    op.create_unique_constraint(None, 'security_control', ['id'])
    op.create_unique_constraint(None, 'security_section', ['id'])
    op.create_unique_constraint(None, 'security_topic', ['id'])
    op.create_unique_constraint(None, 'state', ['id'])
    op.alter_column('user', 'fullname',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.create_unique_constraint(None, 'workflow', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='unique')
    op.alter_column('user', 'fullname',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_constraint(None, 'state', type_='unique')
    op.drop_constraint(None, 'security_topic', type_='unique')
    op.drop_constraint(None, 'security_section', type_='unique')
    op.drop_constraint(None, 'security_control', type_='unique')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_constraint(None, 'label', type_='unique')
    op.drop_constraint(None, 'issue', type_='unique')
    # ### end Alembic commands ###
