"""Addded board schema an defined new relationships

Revision ID: 91ae909fb2fa
Revises: 3992784ddea1
Create Date: 2024-07-27 10:08:18.818446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ae909fb2fa'
down_revision: Union[str, None] = '3992784ddea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_board_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'board_id')
    )
    op.create_index('idx_user_board_association_board_id', 'user_board_association', ['board_id'], unique=False)
    op.create_index('idx_user_board_association_user_id', 'user_board_association', ['user_id'], unique=False)
    op.create_index('idx_issue_label_association_issue_id', 'issue_label_association', ['issue_id'], unique=False)
    op.create_index('idx_issue_label_association_label_id', 'issue_label_association', ['label_id'], unique=False)
    op.drop_constraint('issue_label_association_label_id_fkey', 'issue_label_association', type_='foreignkey')
    op.drop_constraint('issue_label_association_issue_id_fkey', 'issue_label_association', type_='foreignkey')
    op.create_foreign_key(None, 'issue_label_association', 'label', ['label_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'issue_label_association', 'issue', ['issue_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_issue_security_control_association_issue_id', 'issue_security_control_association', ['issue_id'], unique=False)
    op.create_index('idx_issue_security_control_association_security_control_id', 'issue_security_control_association', ['security_control_id'], unique=False)
    op.drop_constraint('issue_security_control_association_issue_id_fkey', 'issue_security_control_association', type_='foreignkey')
    op.drop_constraint('issue_security_control_association_security_control_id_fkey', 'issue_security_control_association', type_='foreignkey')
    op.create_foreign_key(None, 'issue_security_control_association', 'issue', ['issue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'issue_security_control_association', 'security_control', ['security_control_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_project_security_section_association_project_id', 'project_security_section_association', ['project_id'], unique=False)
    op.create_index('idx_project_security_section_association_security_section_id', 'project_security_section_association', ['security_section_id'], unique=False)
    op.drop_constraint('project_security_section_association_project_id_fkey', 'project_security_section_association', type_='foreignkey')
    op.drop_constraint('project_security_section_association_security_section_id_fkey', 'project_security_section_association', type_='foreignkey')
    op.create_foreign_key(None, 'project_security_section_association', 'security_section', ['security_section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_security_section_association', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_project_security_topic_association_project_id', 'project_security_topic_association', ['project_id'], unique=False)
    op.create_index('idx_project_security_topic_association_security_topic_id', 'project_security_topic_association', ['security_topic_id'], unique=False)
    op.drop_constraint('project_security_topic_association_project_id_fkey', 'project_security_topic_association', type_='foreignkey')
    op.drop_constraint('project_security_topic_association_security_topic_id_fkey', 'project_security_topic_association', type_='foreignkey')
    op.create_foreign_key(None, 'project_security_topic_association', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_security_topic_association', 'security_topic', ['security_topic_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_user_issue_association_issue_id', 'user_issue_association', ['issue_id'], unique=False)
    op.create_index('idx_user_issue_association_user_id', 'user_issue_association', ['user_id'], unique=False)
    op.drop_constraint('user_issue_association_user_id_fkey', 'user_issue_association', type_='foreignkey')
    op.drop_constraint('user_issue_association_issue_id_fkey', 'user_issue_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_issue_association', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_issue_association', 'issue', ['issue_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_user_project_association_project_id', 'user_project_association', ['project_id'], unique=False)
    op.create_index('idx_user_project_association_user_id', 'user_project_association', ['user_id'], unique=False)
    op.drop_constraint('user_project_association_project_id_fkey', 'user_project_association', type_='foreignkey')
    op.drop_constraint('user_project_association_user_id_fkey', 'user_project_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_project_association', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_project_association', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflow', sa.Column('board_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workflow', 'board', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'board_id')
    op.drop_constraint(None, 'user_project_association', type_='foreignkey')
    op.drop_constraint(None, 'user_project_association', type_='foreignkey')
    op.create_foreign_key('user_project_association_user_id_fkey', 'user_project_association', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_project_association_project_id_fkey', 'user_project_association', 'project', ['project_id'], ['id'])
    op.drop_index('idx_user_project_association_user_id', table_name='user_project_association')
    op.drop_index('idx_user_project_association_project_id', table_name='user_project_association')
    op.drop_constraint(None, 'user_issue_association', type_='foreignkey')
    op.drop_constraint(None, 'user_issue_association', type_='foreignkey')
    op.create_foreign_key('user_issue_association_issue_id_fkey', 'user_issue_association', 'issue', ['issue_id'], ['id'])
    op.create_foreign_key('user_issue_association_user_id_fkey', 'user_issue_association', 'user', ['user_id'], ['id'])
    op.drop_index('idx_user_issue_association_user_id', table_name='user_issue_association')
    op.drop_index('idx_user_issue_association_issue_id', table_name='user_issue_association')
    op.drop_constraint(None, 'project_security_topic_association', type_='foreignkey')
    op.drop_constraint(None, 'project_security_topic_association', type_='foreignkey')
    op.create_foreign_key('project_security_topic_association_security_topic_id_fkey', 'project_security_topic_association', 'security_topic', ['security_topic_id'], ['id'])
    op.create_foreign_key('project_security_topic_association_project_id_fkey', 'project_security_topic_association', 'project', ['project_id'], ['id'])
    op.drop_index('idx_project_security_topic_association_security_topic_id', table_name='project_security_topic_association')
    op.drop_index('idx_project_security_topic_association_project_id', table_name='project_security_topic_association')
    op.drop_constraint(None, 'project_security_section_association', type_='foreignkey')
    op.drop_constraint(None, 'project_security_section_association', type_='foreignkey')
    op.create_foreign_key('project_security_section_association_security_section_id_fkey', 'project_security_section_association', 'security_section', ['security_section_id'], ['id'])
    op.create_foreign_key('project_security_section_association_project_id_fkey', 'project_security_section_association', 'project', ['project_id'], ['id'])
    op.drop_index('idx_project_security_section_association_security_section_id', table_name='project_security_section_association')
    op.drop_index('idx_project_security_section_association_project_id', table_name='project_security_section_association')
    op.drop_constraint(None, 'issue_security_control_association', type_='foreignkey')
    op.drop_constraint(None, 'issue_security_control_association', type_='foreignkey')
    op.create_foreign_key('issue_security_control_association_security_control_id_fkey', 'issue_security_control_association', 'security_control', ['security_control_id'], ['id'])
    op.create_foreign_key('issue_security_control_association_issue_id_fkey', 'issue_security_control_association', 'issue', ['issue_id'], ['id'])
    op.drop_index('idx_issue_security_control_association_security_control_id', table_name='issue_security_control_association')
    op.drop_index('idx_issue_security_control_association_issue_id', table_name='issue_security_control_association')
    op.drop_constraint(None, 'issue_label_association', type_='foreignkey')
    op.drop_constraint(None, 'issue_label_association', type_='foreignkey')
    op.create_foreign_key('issue_label_association_issue_id_fkey', 'issue_label_association', 'issue', ['issue_id'], ['id'])
    op.create_foreign_key('issue_label_association_label_id_fkey', 'issue_label_association', 'label', ['label_id'], ['id'])
    op.drop_index('idx_issue_label_association_label_id', table_name='issue_label_association')
    op.drop_index('idx_issue_label_association_issue_id', table_name='issue_label_association')
    op.drop_index('idx_user_board_association_user_id', table_name='user_board_association')
    op.drop_index('idx_user_board_association_board_id', table_name='user_board_association')
    op.drop_table('user_board_association')
    op.drop_table('board')
    # ### end Alembic commands ###
