"""Added security_topic.application field

Revision ID: 9b1f13fcce70
Revises: cf73a1fd07d3
Create Date: 2024-07-31 11:22:32.648589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1f13fcce70'
down_revision: Union[str, None] = 'cf73a1fd07d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_topic', sa.Column('application', sa.String(length=280), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_topic', 'application')
    # ### end Alembic commands ###
