"""Added Label.color and Label.description field

Revision ID: 9ed40317e5f5
Revises: 04184a9bd72e
Create Date: 2024-07-23 21:59:43.669270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed40317e5f5'
down_revision: Union[str, None] = '04184a9bd72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'color', ['id'])
    op.add_column('label', sa.Column('description', sa.String(length=280), nullable=True))
    op.add_column('label', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'color')
    op.drop_column('label', 'description')
    op.drop_constraint(None, 'color', type_='unique')
    # ### end Alembic commands ###
