"""Added Issue.is_ready_for_development with default of False

Revision ID: a3708e2db974
Revises: 55ea38f88555
Create Date: 2024-07-19 16:16:11.939911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3708e2db974'
down_revision: Union[str, None] = '55ea38f88555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('ready_for_development', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'ready_for_development')
    # ### end Alembic commands ###
