"""Fix typo in User model for oauth_accounts

Revision ID: ae28dc4554f7
Revises: 7bb4610376ed
Create Date: 2024-07-16 13:19:15.812223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae28dc4554f7'
down_revision: Union[str, None] = '7bb4610376ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
