"""Fixed missing mapping between User and Board

Revision ID: cf73a1fd07d3
Revises: 91ae909fb2fa
Create Date: 2024-07-27 10:29:54.713292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf73a1fd07d3'
down_revision: Union[str, None] = '91ae909fb2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'board', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board', type_='unique')
    # ### end Alembic commands ###
